[config]
reload_apps = true

[config.reload_apps_list]
kitty = true
gtk_theme = true

[templates.kitty]
input_path = '~/.config/matugen/templates/kitty-colors.conf'
output_path = '~/dotfiles/config/kitty/colors.conf'
post_hook = "killall -SIGUSR1 kitty &"

[templates.waybar]
input_path = '~/.config/matugen/templates/colors.css'
output_path = '~/.cache/colors-waybar.css'

[templates.rofi]
input_path = '~/.config/matugen/templates/colors-rofi.rasi'
output_path = '~/.cache/colors-rofi.rasi'

[templates.nvim-theme]
input_path = '~/.config/matugen/templates/nvim-theme.lua'
output_path = '~/.config/nvim/lua/colors/matugen.lua'

[templates.wlogout]
input_path = '~/.config/matugen/templates/colors-wlogout.css'
output_path = '~/.cache/colors-wlogout.css'

[templates.hyprlock-colors]
input_path = '~/.config/matugen/templates/hyprlock-colors.conf'
output_path = '~/.cache/hyprlock-colors.conf'

[templates.swaync]
input_path = '~/.config/matugen/templates/swaync-style.css'
output_path = '~/dotfiles/config/swaync/style.css'
post_hook = "swaync-client -rs && swaync-client -R &"

[templates.gtk3-colors]
input_path = '~/.config/matugen/templates/gtk-3.0-colors.css'
output_path = '~/dotfiles/config/gtk-3.0/colors.css'
post_hook = "~/dotfiles/config/hypr/scripts/gtk.sh &"

[templates.gtk4-colors]
input_path = '~/.config/matugen/templates/gtk-4.0-colors.css'
output_path = '~/dotfiles/config/gtk-4.0/colors.css'

[templates.telegram]
input_path = '~/.config/matugen/templates/telegram.tdesktop-theme'
output_path = '~/.cache/telegram-material-you.tdesktop-theme'


[templates.colors-hyprland]
input_path = '~/.config/matugen/templates/colors-hyprland.conf'
output_path = '~/.cache/colors-hyprland.conf'
post_hook = "hyprctl reload"

[templates.btop]
input_path = '~/.config/matugen/templates/btop.theme'
output_path = '~/dotfiles/config/btop/themes/matugen.theme'

[templates.yazi]
input_path = '~/.config/matugen/templates/yazi-theme.toml'
output_path = '~/dotfiles/config/yazi/theme.toml'
